"""Dataset profiling — real numbers only, no assumptions.

profile_dataset(df) -> dict of row/col/null/dup/dist stats.
run_all() writes docs/phase1a-data-quality-report.md.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]


def profile_dataset(df: pd.DataFrame) -> dict:
    num = df.select_dtypes(include="number")
    return {
        "rows": int(len(df)),
        "columns": list(df.columns),
        "dtypes": {c: str(t) for c, t in df.dtypes.items()},
        "null_counts": df.isna().sum().to_dict(),
        "n_unique": df.nunique().to_dict(),
        "duplicate_rows": int(df.duplicated().sum()),
        "numeric_describe": num.describe().round(3).to_dict(),
    }


def _fmt_table(df: pd.DataFrame, max_rows: int = 30) -> str:
    return df.head(max_rows).to_markdown(index=True)


def recell_findings(df: pd.DataFrame) -> dict:
    r = df["used_to_new_ratio"]
    return {
        "rows": len(df),
        "ratio_describe": r.describe().round(4).to_dict(),
        "ratio_out_of_bounds": int(((r <= 0) | (r > 1.5)).sum()),
        "brand_counts": df["brand"].value_counts().to_dict(),
        "release_year_counts": df["release_year"].value_counts().sort_index().to_dict(),
        "corr_days_used_ratio": round(float(df["days_used"].corr(r)), 4),
        "corr_release_year_ratio": round(float(df["release_year"].corr(r)), 4),
        "corr_storage_ratio": round(float(df["storage_gb"].corr(r)), 4),
        "r2_ratio_on_days_used": round(
            float(1 - np.var(r - np.polyval(np.polyfit(df["days_used"], r, 1), df["days_used"]))
                  / np.var(r)), 4),
        "corr_days_used_release_year": round(float(df["days_used"].corr(df["release_year"])), 4),
        "duplicates": int(df.duplicated().sum()),
        "nulls": df.isna().sum().to_dict(),
        # rule-generation smell test: how many ratio values repeat exactly?
        "top_repeated_ratios": r.round(6).value_counts().head(5).to_dict(),
        # storage degenerate values
        "odd_storage_values": sorted(df.loc[df["storage_gb"] < 8, "storage_gb"].unique().tolist()),
        "odd_ram_values": sorted(df.loc[df["ram"] > 24, "ram"].unique().tolist()),
    }


def mizan_findings(df: pd.DataFrame) -> dict:
    r = df["resale_to_original_ratio"]
    cond = df.groupby("condition_grade")["resale_to_original_ratio"].agg(["count", "mean", "std"]).round(4)
    return {
        "rows": len(df),
        "ratio_describe": r.describe().round(4).to_dict(),
        "ratio_out_of_bounds": int(((r <= 0) | (r > 1.5)).sum()),
        "brand_counts": df["brand"].value_counts().to_dict(),
        "model_nunique": int(df["model"].nunique()),
        "condition_counts": df["condition"].value_counts().to_dict(),
        "unmapped_conditions": int(df["condition_grade"].isna().sum()),
        "battery_range": [float(df["battery_health"].min()), float(df["battery_health"].max())],
        "battery_health_nulls": int(df["battery_health"].isna().sum()),
        "corr_battery_ratio": round(float(df["battery_health"].corr(r)), 4),
        "corr_age_ratio": round(float(df["age_years"].corr(r)), 4),
        # synthetic-generation evidence: real devices show battery/age coupling
        "corr_battery_age": round(float(df["battery_health"].corr(df["age_years"])), 4),
        "corr_storage_ratio": round(float(df["storage_gb"].corr(r)), 4),
        "corr_ram_ratio": round(float(df["ram_gb"].corr(r)), 4),
        "by_condition": cond.to_dict(),
        "duplicates": int(df.duplicated().sum()),
        "nulls": df.isna().sum().to_dict(),
        "top_repeated_ratios": r.round(6).value_counts().head(5).to_dict(),
        # confounding: does condition correlate with age? (older -> worse condition)
        "mean_age_by_condition": df.groupby("condition_grade")["age_years"].mean().round(3).to_dict(),
        "mean_battery_by_condition": df.groupby("condition_grade")["battery_health"].mean().round(2).to_dict(),
        # suspicious regularity: price endings / round numbers
        "resale_round_1000_share": round(float((df["resale_price"] % 1000 == 0).mean()), 4),
    }


def build_report(recell: pd.DataFrame, mizan: pd.DataFrame) -> str:
    rc, mz = recell_findings(recell), mizan_findings(mizan)
    lines = [
        "# Phase 1A — Data Quality Report",
        "",
        "Auto-generated by `src/quality/profile.py` from real files in `data/raw/`.",
        "Numbers below are measured, not assumed.",
        "",
        "## ReCell / ahsan81 (used_phone_data.csv)",
        "",
        f"- Rows: **{rc['rows']}**, exact duplicate rows: {rc['duplicates']}",
        f"- Nulls: {rc['nulls']}",
        f"- `used_to_new_ratio` describe: `{rc['ratio_describe']}`",
        f"- Ratio out of (0, 1.5]: {rc['ratio_out_of_bounds']}",
        f"- Corr(days_used, ratio): {rc['corr_days_used_ratio']} | Corr(release_year, ratio): {rc['corr_release_year_ratio']} | Corr(storage_gb, ratio): {rc['corr_storage_ratio']}",
        f"- **R²(ratio ~ days_used) = {rc['r2_ratio_on_days_used']}** — depreciation is almost perfectly linear; consistent with modeled/normalized prices, not raw market data",
        f"- Corr(days_used, release_year): {rc['corr_days_used_release_year']}",
        f"- Brand counts: {rc['brand_counts']}",
        f"- Release years: {rc['release_year_counts']}",
        f"- Top repeated ratio values (rule-generation check): {rc['top_repeated_ratios']}",
        f"- Storage < 8 GB values present: {rc['odd_storage_values']} (likely tablets/other devices)",
        f"- RAM > 24 GB values: {rc['odd_ram_values']}",
        "",
        "## mizan121 used-phone-dataset (used_phone.csv)",
        "",
        f"- Rows: **{mz['rows']}**, exact duplicates: {mz['duplicates']}, unique models: {mz['model_nunique']}",
        f"- Nulls: {mz['nulls']}",
        f"- `resale_to_original_ratio` describe: `{mz['ratio_describe']}`",
        f"- Ratio out of (0, 1.5]: {mz['ratio_out_of_bounds']}",
        f"- Battery health range: {mz['battery_range']} (nulls: {mz['battery_health_nulls']})",
        f"- Corr(battery_health, ratio): {mz['corr_battery_ratio']} | Corr(age_years, ratio): {mz['corr_age_ratio']}",
        f"- **Corr(battery_health, age_years) = {mz['corr_battery_age']}** — physically implausible independence (real batteries degrade with age)",
        f"- Corr(storage_gb, ratio): {mz['corr_storage_ratio']} | Corr(ram_gb, ratio): {mz['corr_ram_ratio']} — storage/RAM carry ~zero price signal, inconsistent with real markets",
        f"- Conditions: {mz['condition_counts']} (unmapped: {mz['unmapped_conditions']})",
        f"- Ratio by condition: `{mz['by_condition']}`",
        f"- Mean age by condition: {mz['mean_age_by_condition']}",
        f"- Mean battery by condition: {mz['mean_battery_by_condition']}",
        f"- resale_price % 1000 == 0 share: {mz['resale_round_1000_share']}",
        f"- Top repeated ratios: {mz['top_repeated_ratios']}",
        f"- Brand counts: {mz['brand_counts']}",
        "",
        "## Cross-dataset compatibility",
        "",
        "| Relationship | Datasets |",
        "|---|---|",
        "| A — EXACT JOIN | none (different populations, no shared entity key) |",
        "| B — ENRICHMENT | ReCell spec cols could enrich device variants IF model identity existed (it does not — brand only) |",
        "| C — STATISTICAL PRIOR | ReCell + mizan121 both serve as structure/prior for ratio learning |",
        "| D — NEVER MERGE | row-level join between them is invalid |",
        "",
    ]
    return "\n".join(lines)


def run_all() -> Path:
    recell = pd.read_parquet(ROOT / "data" / "interim" / "recell.parquet")
    mizan = pd.read_parquet(ROOT / "data" / "interim" / "mizan121.parquet")
    report = build_report(recell, mizan)
    out = ROOT / "docs" / "phase1a-data-quality-report.md"
    out.write_text(report, encoding="utf-8")
    return out


if __name__ == "__main__":
    print(run_all())
